apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-server
  labels:
    app: {{ template "fullname" . }}-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  {{ if .Values.ssl.enabled }}
  - name: http
    port: 80
    targetPort: http
  {{ else }}
  - name: https
    port: 443
    targetPort: https
  {{ end }}
  selector:
    app: {{ template "fullname" . }}-server
